# Ejemplo de carga y limpieza de un dataset con Pandas

En este notebook vamos a trabajar con un archivo CSV que contiene datos ficticios de clientes y compras.

El objetivo es aprender a:

1. Cargar un archivo CSV con `pandas`.
2. Explorar rápidamente un dataset.
3. Detectar valores nulos y duplicados.
4. Limpiar textos inconsistentes.
5. Convertir columnas al tipo de dato correcto.
6. Detectar valores imposibles o anómalos.
7. Eliminar o corregir registros problemáticos.
8. Guardar el dataset limpio en un nuevo CSV.

> El archivo utilizado es **`ventas_clientes_sucio.csv`**.

## 1. Importar Pandas

`pandas` es una de las librerías más utilizadas en Python para trabajar con datos tabulares.

Normalmente se importa utilizando el alias `pd`.

In [ ]:
import pandas as pd

## 2. Cargar el archivo CSV

La función `pd.read_csv()` permite leer un archivo CSV y convertirlo en un **DataFrame**.

Un DataFrame es una estructura similar a una tabla de Excel: tiene filas y columnas.

In [ ]:
df = pd.read_csv("ventas_clientes_sucio.csv")

df

,id_cliente,nombre,ciudad,email,edad,importe_compra,fecha_compra,metodo_pago
0,1,Ana López,Barcelona,ana@email.com,25,120.50,2026-01-15,Tarjeta
1,2,MARC GARCIA,barcelona,marc@email.com,31,"89,90",16/01/2026,tarjeta
2,3,Lucía Pérez,Madrid,lucia@email.com,NaN,210.00,2026/01/17,Efectivo
3,4,Jordi Serra,BARCELONA,jordi@email.com,42,-15.00,18-01-2026,Transferencia
4,5,Marta Ruiz,Valencia,NaN,29,75.20,2026-01-19,Tarjeta
5,6,Pablo Martín,madrid,pablo@email.com,35 años,130.00,2026-01-20,efectivo
6,7,Clara Soler,Barcelona,clara@email.com,27,NaN,2026-01-21,Tarjeta
7,8,David Gil,Valencia,david@email.com,200,95.60,2026-01-22,Transferencia
8,9,Elena Costa,Sevilla,elena@email.com,33,abc,2026-01-23,Tarjeta
9,10,Nil Bosch,Barcelona,nil@email.com,24,110.00,fecha_desconocida,Efectivo
10,11,Sara Mora,MADRID,sara@email.com,30,140.30,2026-01-25,tarjeta
11,11,Sara Mora,MADRID,sara@email.com,30,140.30,2026-01-25,tarjeta
12,12,Óscar León,Valencia,oscar@email.com,28,67.40,2026-01-26,Transferencia
13,13,Nora Vidal,NaN,nora@email.com,26,155.00,2026-01-27,Tarjeta
14,14,Leo Ramos,Barcelona,leo@email.com,-3,99.99,2026-01-28,Efectivo

## 3. Primer vistazo al dataset

Antes de limpiar nada, conviene entender qué tenemos.

Algunos comandos básicos:

- `head()` → muestra las primeras filas.
- `shape` → indica el número de filas y columnas.
- `columns` → muestra los nombres de las columnas.
- `info()` → muestra tipos de datos y valores no nulos.
- `describe()` → resume las columnas numéricas.

In [ ]:
df.head()

,id_cliente,nombre,ciudad,email,edad,importe_compra,fecha_compra,metodo_pago
0,1,Ana López,Barcelona,ana@email.com,25,120.50,2026-01-15,Tarjeta
1,2,MARC GARCIA,barcelona,marc@email.com,31,"89,90",16/01/2026,tarjeta
2,3,Lucía Pérez,Madrid,lucia@email.com,NaN,210.00,2026/01/17,Efectivo
3,4,Jordi Serra,BARCELONA,jordi@email.com,42,-15.00,18-01-2026,Transferencia
4,5,Marta Ruiz,Valencia,NaN,29,75.20,2026-01-19,Tarjeta

In [ ]:
print("Dimensiones:", df.shape)
print("\nColumnas:")
print(df.columns.tolist())

Dimensiones: (15, 8)

Columnas:
['id_cliente', 'nombre', 'ciudad', 'email', 'edad', 'importe_compra', 'fecha_compra', 'metodo_pago']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_cliente      15 non-null     int64
 1   nombre          15 non-null     object
 2   ciudad          14 non-null     object
 3   email           14 non-null     object
 4   edad            14 non-null     object
 5   importe_compra  14 non-null     object
 6   fecha_compra    15 non-null     object
 7   metodo_pago     15 non-null     object
dtypes: int64(1), object(7)
memory usage: 1.1+ KB

### ¿Qué problemas podemos observar?

Este dataset contiene errores frecuentes en datos reales:

- espacios al principio o al final de algunos textos;
- ciudades escritas con distintas combinaciones de mayúsculas y minúsculas;
- valores nulos;
- filas duplicadas;
- edades almacenadas como texto;
- edades imposibles;
- importes escritos con coma decimal;
- importes negativos;
- texto dentro de una columna numérica;
- fechas con formatos diferentes;
- fechas no válidas.

Vamos a corregirlos paso a paso.

## 4. Detectar valores nulos

`isna()` identifica los valores ausentes.

Si añadimos `.sum()`, podemos contar cuántos valores nulos hay en cada columna.

In [ ]:
df.isna().sum()

id_cliente        0
nombre            0
ciudad            1
email             1
edad              1
importe_compra    1
fecha_compra      0
metodo_pago       0
dtype: int64

También podemos calcular el porcentaje de valores nulos por columna.

In [ ]:
(df.isna().mean() * 100).round(2)

id_cliente        0.00
nombre            0.00
ciudad            6.67
email             6.67
edad              6.67
importe_compra    6.67
fecha_compra      0.00
metodo_pago       0.00
dtype: float64

## 5. Detectar filas duplicadas

`duplicated()` devuelve `True` para las filas repetidas.

In [ ]:
df[df.duplicated()]

,id_cliente,nombre,ciudad,email,edad,importe_compra,fecha_compra,metodo_pago
11,11,Sara Mora,MADRID,sara@email.com,30,140.30,2026-01-25,tarjeta

Eliminamos duplicados con `drop_duplicates()`.

In [ ]:
df = df.drop_duplicates().copy()

print("Filas después de eliminar duplicados:", len(df))

Filas después de eliminar duplicados: 14

## 6. Limpiar columnas de texto

Primero eliminamos espacios innecesarios utilizando `str.strip()`.

Después normalizamos algunas columnas para que tengan un formato consistente.

In [ ]:
columnas_texto = ["nombre", "ciudad", "email", "metodo_pago"]

for columna in columnas_texto:
    df[columna] = df[columna].astype("string").str.strip()

df.head()

,id_cliente,nombre,ciudad,email,edad,importe_compra,fecha_compra,metodo_pago
0,1,Ana López,Barcelona,ana@email.com,25,120.50,2026-01-15,Tarjeta
1,2,MARC GARCIA,barcelona,marc@email.com,31,"89,90",16/01/2026,tarjeta
2,3,Lucía Pérez,Madrid,lucia@email.com,NaN,210.00,2026/01/17,Efectivo
3,4,Jordi Serra,BARCELONA,jordi@email.com,42,-15.00,18-01-2026,Transferencia
4,5,Marta Ruiz,Valencia,<NA>,29,75.20,2026-01-19,Tarjeta

Ahora ponemos nombres, ciudades y métodos de pago en un formato más uniforme.

`str.title()` convierte, por ejemplo:

- `BARCELONA` → `Barcelona`
- `tarjeta` → `Tarjeta`

In [ ]:
df["nombre"] = df["nombre"].str.title()
df["ciudad"] = df["ciudad"].str.title()
df["metodo_pago"] = df["metodo_pago"].str.title()

df[["nombre", "ciudad", "metodo_pago"]]

          nombre     ciudad    metodo_pago
0      Ana López  Barcelona        Tarjeta
1    Marc Garcia  Barcelona        Tarjeta
2    Lucía Pérez     Madrid       Efectivo
3    Jordi Serra  Barcelona  Transferencia
4     Marta Ruiz   Valencia        Tarjeta
5   Pablo Martín     Madrid       Efectivo
6    Clara Soler  Barcelona        Tarjeta
7      David Gil   Valencia  Transferencia
8    Elena Costa    Sevilla        Tarjeta
9      Nil Bosch  Barcelona       Efectivo
10     Sara Mora     Madrid        Tarjeta
12    Óscar León   Valencia  Transferencia
13    Nora Vidal       <NA>        Tarjeta
14     Leo Ramos  Barcelona       Efectivo

## 7. Limpiar la columna de edad

La columna `edad` contiene valores como:

- `"25"`
- `"35 años"`
- valores vacíos
- edades imposibles como `200` o `-3`

Primero extraemos la parte numérica y la convertimos a número.

In [ ]:
df["edad"] = (
    df["edad"]
    .astype("string")
    .str.extract(r"(\d+)", expand=False)
)

df["edad"] = pd.to_numeric(df["edad"], errors="coerce")

df[["nombre", "edad"]]

          nombre  edad
0      Ana López    25
1    Marc Garcia    31
2    Lucía Pérez  <NA>
3    Jordi Serra    42
4     Marta Ruiz    29
5   Pablo Martín    35
6    Clara Soler    27
7      David Gil   200
8    Elena Costa    33
9      Nil Bosch    24
10     Sara Mora    30
12    Óscar León    28
13    Nora Vidal    26
14     Leo Ramos     3

`errors="coerce"` convierte los valores que no se pueden transformar en número a `NaN`.

Ahora consideramos inválidas las edades menores de 0 o mayores de 100.

In [ ]:
df.loc[(df["edad"] < 0) | (df["edad"] > 100), "edad"] = pd.NA

df[["nombre", "edad"]]

          nombre  edad
0      Ana López    25
1    Marc Garcia    31
2    Lucía Pérez  <NA>
3    Jordi Serra    42
4     Marta Ruiz    29
5   Pablo Martín    35
6    Clara Soler    27
7      David Gil  <NA>
8    Elena Costa    33
9      Nil Bosch    24
10     Sara Mora    30
12    Óscar León    28
13    Nora Vidal    26
14     Leo Ramos     3

Podemos rellenar las edades que faltan utilizando, por ejemplo, la **mediana**.

La mediana suele ser más robusta que la media cuando existen valores extremos.

In [ ]:
mediana_edad = int(df["edad"].median().round())

df["edad"] = df["edad"].fillna(mediana_edad)

print("Mediana utilizada:", mediana_edad)
df[["nombre", "edad"]]

print("Mediana utilizada:", mediana_edad)
df[["nombre", "edad"]]

Mediana utilizada: 28
Mediana utilizada: 28

          nombre  edad
0      Ana López    25
1    Marc Garcia    31
2    Lucía Pérez    28
3    Jordi Serra    42
4     Marta Ruiz    29
5   Pablo Martín    35
6    Clara Soler    27
7      David Gil    28
8    Elena Costa    33
9      Nil Bosch    24
10     Sara Mora    30
12    Óscar León    28
13    Nora Vidal    26
14     Leo Ramos     3

## 8. Limpiar la columna de importe

El importe contiene varios problemas:

- números con punto decimal;
- números con coma decimal (`89,90`);
- texto (`abc`);
- valores nulos;
- valores negativos.

Primero sustituimos la coma decimal por un punto.

In [ ]:
df["importe_compra"] = (
    df["importe_compra"]
    .astype("string")
    .str.replace(",", ".", regex=False)
)

df["importe_compra"] = pd.to_numeric(df["importe_compra"], errors="coerce")

df[["nombre", "importe_compra"]]

          nombre  importe_compra
0      Ana López           120.5
1    Marc Garcia            89.9
2    Lucía Pérez           210.0
3    Jordi Serra           -15.0
4     Marta Ruiz            75.2
5   Pablo Martín           130.0
6    Clara Soler            <NA>
7      David Gil            95.6
8    Elena Costa            <NA>
9      Nil Bosch           110.0
10     Sara Mora           140.3
12    Óscar León            67.4
13    Nora Vidal           155.0
14     Leo Ramos           99.99

Los importes negativos no tienen sentido en este ejemplo, por lo que los convertimos en valores nulos.

In [ ]:
df.loc[df["importe_compra"] < 0, "importe_compra"] = pd.NA

df[["nombre", "importe_compra"]]

          nombre  importe_compra
0      Ana López           120.5
1    Marc Garcia            89.9
2    Lucía Pérez           210.0
3    Jordi Serra            <NA>
4     Marta Ruiz            75.2
5   Pablo Martín           130.0
6    Clara Soler            <NA>
7      David Gil            95.6
8    Elena Costa            <NA>
9      Nil Bosch           110.0
10     Sara Mora           140.3
12    Óscar León            67.4
13    Nora Vidal           155.0
14     Leo Ramos           99.99

Podemos rellenar los importes ausentes con la mediana de la columna.

In [ ]:
mediana_importe = df["importe_compra"].median()

df["importe_compra"] = df["importe_compra"].fillna(mediana_importe)

print("Mediana utilizada:", mediana_importe)

Mediana utilizada: 110.0

## 9. Convertir la columna de fecha

Las fechas aparecen en formatos distintos.

`pd.to_datetime()` intenta convertirlas a un tipo de fecha real.

Con `errors="coerce"`, las fechas imposibles se convierten en `NaT` (*Not a Time*).

In [ ]:
df["fecha_compra"] = pd.to_datetime(
    df["fecha_compra"],
    errors="coerce",
    dayfirst=True
)

df[["nombre", "fecha_compra"]]

/tmp/ipykernel_696/3305220230.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df["fecha_compra"] = pd.to_datetime(

          nombre fecha_compra
0      Ana López   2026-01-15
1    Marc Garcia          NaT
2    Lucía Pérez          NaT
3    Jordi Serra          NaT
4     Marta Ruiz   2026-01-19
5   Pablo Martín   2026-01-20
6    Clara Soler   2026-01-21
7      David Gil   2026-01-22
8    Elena Costa   2026-01-23
9      Nil Bosch          NaT
10     Sara Mora   2026-01-25
12    Óscar León   2026-01-26
13    Nora Vidal   2026-01-27
14     Leo Ramos   2026-01-28

Podemos comprobar qué registros tienen una fecha inválida.

In [ ]:
df[df["fecha_compra"].isna()]

,id_cliente,nombre,ciudad,email,edad,importe_compra,fecha_compra,metodo_pago
1,2,Marc Garcia,Barcelona,marc@email.com,31,89.9,NaT,Tarjeta
2,3,Lucía Pérez,Madrid,lucia@email.com,28,210.0,NaT,Efectivo
3,4,Jordi Serra,Barcelona,jordi@email.com,42,110.0,NaT,Transferencia
9,10,Nil Bosch,Barcelona,nil@email.com,24,110.0,NaT,Efectivo

En este ejemplo eliminaremos las filas cuya fecha no se puede recuperar de forma fiable.

In [ ]:
df = df.dropna(subset=["fecha_compra"]).copy()

## 10. Tratar otros valores ausentes

En este ejemplo:

- si falta la ciudad, escribiremos `"Desconocida"`;
- si falta el email, escribiremos `"No disponible"`.

En un proyecto real, la decisión dependerá del significado de cada variable.

In [ ]:
df["ciudad"] = df["ciudad"].fillna("Desconocida")
df["email"] = df["email"].fillna("No disponible")

## 11. Comprobar el resultado final

Después de limpiar los datos, conviene revisar de nuevo:

- valores nulos;
- duplicados;
- tipos de datos;
- primeras filas.

In [ ]:
print("Valores nulos:")
print(df.isna().sum())

print("\nDuplicados:", df.duplicated().sum())

print("\nDimensiones finales:", df.shape)

Valores nulos:
id_cliente        0
nombre            0
ciudad            0
email             0
edad              0
importe_compra    0
fecha_compra      0
metodo_pago       0
dtype: int64

Duplicados: 0

Dimensiones finales: (10, 8)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 14
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_cliente      10 non-null     int64
 1   nombre          10 non-null     string
 2   ciudad          10 non-null     string
 3   email           10 non-null     string
 4   edad            10 non-null     Int64
 5   importe_compra  10 non-null     Float64
 6   fecha_compra    10 non-null     datetime64[ns]
 7   metodo_pago     10 non-null     string
dtypes: Float64(1), Int64(1), datetime64[ns](1), int64(1), string(4)
memory usage: 740.0 bytes

In [ ]:
df

,id_cliente,nombre,ciudad,email,edad,importe_compra,fecha_compra,metodo_pago
0,1,Ana López,Barcelona,ana@email.com,25,120.5,2026-01-15,Tarjeta
4,5,Marta Ruiz,Valencia,No disponible,29,75.2,2026-01-19,Tarjeta
5,6,Pablo Martín,Madrid,pablo@email.com,35,130.0,2026-01-20,Efectivo
6,7,Clara Soler,Barcelona,clara@email.com,27,110.0,2026-01-21,Tarjeta
7,8,David Gil,Valencia,david@email.com,28,95.6,2026-01-22,Transferencia
8,9,Elena Costa,Sevilla,elena@email.com,33,110.0,2026-01-23,Tarjeta
10,11,Sara Mora,Madrid,sara@email.com,30,140.3,2026-01-25,Tarjeta
12,12,Óscar León,Valencia,oscar@email.com,28,67.4,2026-01-26,Transferencia
13,13,Nora Vidal,Desconocida,nora@email.com,26,155.0,2026-01-27,Tarjeta
14,14,Leo Ramos,Barcelona,leo@email.com,3,99.99,2026-01-28,Efectivo

## 12. Crear alguna variable nueva

Una vez limpio el dataset, podemos empezar a transformarlo.

Por ejemplo, podemos crear una categoría de compra según el importe.

In [ ]:
df["categoria_compra"] = pd.cut(
    df["importe_compra"],
    bins=[0, 100, 150, float("inf")],
    labels=["Baja", "Media", "Alta"],
    include_lowest=True
)

df[["nombre", "importe_compra", "categoria_compra"]]

          nombre  importe_compra categoria_compra
0      Ana López           120.5            Media
4     Marta Ruiz            75.2             Baja
5   Pablo Martín           130.0            Media
6    Clara Soler           110.0            Media
7      David Gil            95.6             Baja
8    Elena Costa           110.0            Media
10     Sara Mora           140.3            Media
12    Óscar León            67.4             Baja
13    Nora Vidal           155.0             Alta
14     Leo Ramos           99.99             Baja

## 13. Ejemplos rápidos de análisis

Con el dataset limpio ya podemos hacer análisis sencillos.

In [ ]:
# Importe medio por ciudad
df.groupby("ciudad")["importe_compra"].mean().round(2)

ciudad
Barcelona      110.16
Desconocida     155.0
Madrid         135.15
Sevilla         110.0
Valencia         79.4
Name: importe_compra, dtype: Float64

In [ ]:
# Número de compras por método de pago
df["metodo_pago"].value_counts()

metodo_pago
Tarjeta          6
Efectivo         2
Transferencia    2
Name: count, dtype: Int64

## 14. Guardar el dataset limpio

Finalmente podemos exportar el DataFrame limpio a un nuevo archivo CSV.

In [ ]:
df.to_csv("ventas_clientes_limpio.csv", index=False, encoding="utf-8-sig")

print("Archivo guardado correctamente.")

Archivo guardado correctamente.

# Resumen

El flujo básico de limpieza de datos con Pandas suele ser:

**Cargar → explorar → detectar errores → limpiar → validar → guardar**

Funciones utilizadas en este ejemplo:

```python
pd.read_csv()
df.head()
df.info()
df.isna()
df.duplicated()
df.drop_duplicates()
str.strip()
str.title()
pd.to_numeric()
pd.to_datetime()
fillna()
dropna()
groupby()
value_counts()
to_csv()
```

Este proceso se conoce habitualmente como **data cleaning** o **data preprocessing**.